sudo: required
services:
  - docker

before_install:
  - docker build -t uwaibel/docker-react -f Dockerfile.dev .

script:
  - docker run -it -e CI=true uwaibel/docker-react npm run test -- --coverage

#AWS deployment settings
deploy:
  provider: elasticbeanstalk
  region: ":eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-741157268730"
  bucket_path: "Docker-env"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY   
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"  